version: '3.8'

services:
  megamind-db-mysql:
    image: mysql:8.0
    container_name: megamind-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-megamind_root_pass}
      MYSQL_DATABASE: megamind_database
      MYSQL_USER: megamind_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-megamind_secure_pass}
    volumes:
      - megamind_db_data:/var/lib/mysql
      - ./context_system:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - megamind-network

  # Redis for caching (Phase 2)
  megamind-redis:
    image: redis:7-alpine
    container_name: megamind-redis
    ports:
      - "6380:6379"
    volumes:
      - megamind_redis_data:/data
    restart: unless-stopped
    networks:
      - megamind-network

volumes:
  megamind_db_data:
    driver: local
  megamind_redis_data:
    driver: local

networks:
  megamind-network:
    driver: bridge